import Head from "next/head";
import Card from "../../components/card";
import { useState } from "react";
import { useRouter } from "next/router";
// import { Route, Routes, useNavigate } from "react-router-dom";
// import InputForm from "../../components/form";

export default function Home() {
  // const navigate = useNavigate();
  const router = useRouter();

  const onContinueHandler = () => {
    router.push({
      pathname: "/dashboard",
      query: { id: "123" },
      state: { name: "John" },
    });
  };

  return (
    <>
      <Head>
        <title>Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Jai Ganesha */}
        <Card>
          <p
            className="my-2 mx-auto 
      font-semibold
      text-lg 
      p-2">
            Do You want to build your Resume...
          </p>
          <button
            onClick={onContinueHandler}
            className="
    bg-white
    text-teal-900 
    w-1/2 
    my-auto 
    mx-auto
    rounded-md
    p-2
    text-lg
    ">
            Continue
          </button>
        </Card>
      </main>

      {/* <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/user-input" element={<InputForm />} />
      </Routes> */}
    </>
  );
}
